### PR TITLE
add more tests and change getSecret to getHeader

### LINKED ISSUE #3: Address outstanding Testing / CI issues
- [ ] Could you please set up something like Travis to automatically test the code on each check in and put a badge in GitHub to tell us if tests are passing?
  TODO
- [ ] In test-basic.js I would expect a test to confirm that the buffer is the right size. You can expose the default buffer size as a property on the static newable object (e.g. admin.defaultSecretSizeInBytes or admin.prototype.defaultSecretSizeInBytes, for no good reason I tend to have a preference for the former over the later). I would also expect a test showing that setSecret works although if you adopt my proposal above you won't need that.
  TODO:
- [ ] Just for chuckles I would include at least one request with a request body and see that it is both properly accepted and rejected.
  TODO:

### PR DESCRIPTION
**Pull request by cicorias**
intend to close #3

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/salti-admin/4)

### CODE REVIEW

**Comment by cicorias** [comment]
@yaronyg fyi - changes pushed..

**Comment by yaronyg** [comment]
Reviewed 3 of 7 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_[lib/index.js, line 5 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBUGAyTjeqdJ_Z_9Y2q:-KBUGAyTjeqdJ_Z_9Y2r:1469299575) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/lib/index.js#L5)):_
Personally I would have called this secureCompare just to drive home the fact that something special is going on here.

---

_[lib/index.js, line 24 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBUBWSE9vPOCqy2wd36:-KBUBWSE9vPOCqy2wd37:1767685548) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/lib/index.js#L24)):_
Please use our JSCS file config. Amongst other things it requires brackets on IF statements. Please add .jscsrc, .jshintrc and .editorconfig from Thali_CordovaPlugin and please check if we are passing.

---

_[lib/index.js, line 42 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBUC0g5uYlSykh7Of2H:-KBUC0g5uYlSykh7Of2I:1341067046) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/lib/index.js#L42)):_
Since you return above why do you need an else?

---

_[lib/index.js, line 46 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBUC3nOmFjOmp3iZH1O:-KBUC3nOmFjOmp3iZH1P:-1130025330) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/lib/index.js#L46)):_
Same issue here, if you return above why do you need an else?

---

_[lib/index.js, line 47 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBUC9Wu-XlB_ugXSeo4:-KBUC9Wu-XlB_ugXSeo5:538262959) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/lib/index.js#L47)):_
Aren't we going to drown the logs? Using say a local PouchDB replication could easily have thousands of messages in a very short period of time.

---

_[lib/index.js, line 49 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBUCKbtBcvckWvb4Kgl:-KBUCKbtBcvckWvb4Kgm:-29244251) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/lib/index.js#L49)):_
Why do we need to check if there is a secret? The code above will throw if there is no secret. So I think we can remove this whole if statement.

---

_[package.json, line 25 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBU9dGCu9p5PmXdbjd2:-KBU9dGCu9p5PmXdbjd3:-1683757026) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/package.json#L25)):_
The use of debug is a problem because we need to have a unified logging framework, we have adopted Winston. We needed something that was configurable so we could do debug or normal builds. We don't want to have to figure out how to override the logging here. So it would be very nice if you could use Winston too. Ideally there would be a way for us to pass in our own logger object, see thalilogger.js in thali_CordovaPlugin to see what I mean.

---

_[test/test-adminacl.js, line 157 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBUEDBeFxh3ipr-CcTT:-KBUEDBfF-Jm0dpLK2O9:1573806012) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/test/test-adminacl.js#L157)):_
I'm confused! You use adminACL but then you make a get request without an authorization header and it works?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/salti-admin/4)_

**Comment by cicorias** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_[lib/index.js, line 5 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBUGAyTjeqdJ_Z_9Y2q:-KBUPSX6G5jJ55Ccn-YD:-499146009) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/lib/index.js#L5)):_
Done.

---

_[lib/index.js, line 24 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBUBWSE9vPOCqy2wd36:-KBUMsUil-ph5cdAbENl:-610076330) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/lib/index.js#L24)):_
I am using it. check the repository. adding brackets

---

_[lib/index.js, line 42 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBUC0g5uYlSykh7Of2H:-KBUPVN5T7CAGG6FQyCK:-499146009) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/lib/index.js#L42)):_
Done.

---

_[lib/index.js, line 46 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBUC3nOmFjOmp3iZH1O:-KBUPWm-nf5xyS53-4Hv:-499146009) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/lib/index.js#L46)):_
Done.

---

_[lib/index.js, line 47 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBUC9Wu-XlB_ugXSeo4:-KBUN48E9evcW1EPPy1o:1784182797) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/lib/index.js#L47)):_
well, no. debug logs to console and only gets turned on if the env var DEBUG=salti-admin:adminacl is specifically set.

---

_[lib/index.js, line 49 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBUCKbtBcvckWvb4Kgl:-KBUPYdgVuigGSOLYoGt:-499146009) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/lib/index.js#L49)):_
Done.

---

_[package.json, line 25 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBU9dGCu9p5PmXdbjd2:-KBUNF4qfCEQHZnL8TZs:802521109) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/package.json#L25)):_
this is the standard debug tool that comes with Express. this is a standalone tool - instrumenting with something else is certainly an option and this is already configurable via environment variables.

I'll add another issue for this to use Winston and an ability to define external.

---

_[test/test-adminacl.js, line 157 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBUEDBeFxh3ipr-CcTT:-KBUNdZlZ8L2R27Y9jV2:660469637) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/test/test-adminacl.js#L157)):_
this isn't the request. this is just setting up the express routes. 

And the real test is below with the `request(...)` calls within the `it` block

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/salti-admin/4)_

**Comment by yaronyg** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[lib/index.js, line 42 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBUC0g5uYlSykh7Of2H:-KBUg9slmRzLT9XTF2wb:634719653) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/lib/index.js#L42)):_
Actually it's not done. The else if is still there. You just need the if, not the else.

---

_[lib/index.js, line 47 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBUC9Wu-XlB_ugXSeo4:-KBUgOlYcAWpD_tA-5Nd:-1178807963) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/lib/index.js#L47)):_
Good answer!

---

_[package.json, line 25 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBU9dGCu9p5PmXdbjd2:-KBUgWsD2VWx3k9Fiy76:-1400235719) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/package.json#L25)):_
Given that debug is essentially harmless I would suggest you file that bug and stick it in the icebox. We have more important fish to fry right now.

---

_[test/test-adminacl.js, line 157 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBUEDBeFxh3ipr-CcTT:-KBUge1Wg3_mlJChNpf5:1566078597) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/test/test-adminacl.js#L157)):_
I'm going to go back into my hole now. Sigh.... Sorry to bother you with my stupidity.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/salti-admin/4)_

**Comment by cicorias** [comment]
this also closes #3 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[lib/index.js, line 42 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBUC0g5uYlSykh7Of2H:-KBVjg9ef-D_KBmRQyWi:-196871497) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/lib/index.js#L42)):_
Done.Done.. 

---

_[package.json, line 25 [r2]](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-KBU9dGCu9p5PmXdbjd2:-KBVjo27oonyh42Y_dlW:-1682119023) ([raw file](https://github.com/thaliproject/salti-admin/blob/7ad858b912bb1fd026b8bc22e081adc45e48c423/package.json#L25)):_
created #5 

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/salti-admin/4#-:-KBVkFTtd19sZM9GT7fe:1330412167)_

**Comment by yaronyg** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/salti-admin/4)_

**Pull request merged**
